### ISSUE TITLE
dev server not working

### ISSUE THREAD

**Issue by sgtpenguin** [ravorona/sage#11]
I may be missing something fundamental here, but I cannot get the dev server to work.  Upon `yarn dev` the page returns `Cannot GET /`.  Have you ever run into this?

If I first run `yarn build` and access the site through a server provided by [Local](https://localwp.com/), I can see that it is working, but I can't figure out how to get a dev server up through vite.  I tried setting `HMR_ENTRYPOINT` to the address provided by Local (http://localhost:10008/) but that didn't do the trick.

Thank you for any guidance you can give.

**Comment by ravorona** [comment]
Hi,
I have never tried `localwp` but it should work nonetheless. For a local installation, you would need to:
- Run `yarn dev`
- Check if the dev server is running properly (The devServer only serves the assets and not the entire WordPress application). By default the devServer at its root path serve nothing that's why you have the `Cannot Get /`. The assets keep their relative paths, so you need to check for example: `http://localhost:3000/resources/scripts/main.ts`
- Enable hot reload by setting `HMR_ENABLED` to true in your `.env`
This tell your wordpress application to load assets from the `HMR_ENTRYPOINT` instead of the `public` or `dist` folder
- Run your wordpress application normally from its domain name (not the HMR one). `http://wordpress.local` for example, from the `localwp` one in your case i mean.

Hope this help you. 👋
